language: ruby
cache: bundler
rvm:
- 2.4.1
script:
- bash ./_scripts/update.sh
branches:
  only:
  - gh-pages
env:
  secure: FH4jr+KKaYy6vvVe5bre8zTnbsN80V5beb/jXN9KvvsSRIPnltQAugnW34VymrWQ9I+2SQqL3ouNK7kuhM8yH/sa2x8iZGylQtBF7VktckmXLAZs0VIJ/+TtMPxZx9PYDEqjEyOYChE3JoNkOMkt0HaxES2AgI2TmUppIVxWIyN2rPdBwCn7npFxCKsC9TybqgKl3xThQlToSkoY0cKAjv08cwfFmnIFt+sOlzAJuvIujJIrVJsPFMZq3EBiHjgDThMSFSUeCAkBc3LzWO56+S2AZJ85YeEF6Q9Mu5sBLVVaowlyJX4xqOtHuwm/1cek0N0i1uvULmK/XI4EKKM1gVUKO1yL10Rh784jRhxJhX6SZUSwyFGsErllKW77YKGu3Rw64Lb62kP0lV+0vXjhdQ1i8N/PgsFTEpWxZzBpzfoVNZ1DpRa0zpHgs1RwIk9CajujwA4g6OzaA5pNtznpXiiwrdp5GVDxn+fwH62T0YMXoI2rdd1nf+bWXl++jJ5k+xBUn6UWwXisgHFb5UV36g/5DXczehwGtkZWIeqCBICyi+TkFHfZSl2+qxAT9LAp6UbPmycmknDQNKpC7zn9xH9kybX7o4ku77J36lCcIJmGQWqKCvLxP2fZqce4Ob+nZsWdixiFM2uoWN8w5z0ITFtcsiasc8oFyG+4f7nfvmQ=
