source 'http://rubygems.org'

gem 'activesupport'
gem 'dotenv'
gem 'github-pages'
gem 'hashie'
gem 'html-proofer'
gem 'httparty'
gem 'polylines'
gem 'rake'
gem 'strava-ruby-client', path: '~/source/strava-ruby-client'
gem 'webrick'