source 'http://rubygems.org'

gem 'activesupport'
gem 'dotenv'
gem 'jekyll', '~> 4.4'
gem 'jekyll-paginate', '~> 1.1'
gem 'jekyll-redirect-from', '~> 0.17.0'
gem 'jekyll-sass-converter', '~> 3.1'
gem 'jekyll-sitemap', '~> 1.4'
gem 'hashie'
gem 'html-proofer'
gem 'json'
gem 'httparty'
gem 'polylines'
gem 'rake'
gem 'strava-ruby-client'
gem 'jekyll-md', '~> 0.2.0'
gem 'webrick'
gem 'wdm', '>= 0.1.0', install_if: Gem.win_platform?