name: strava
on:
  workflow_dispatch:
  schedule:
    - cron: '00 01,13 * * *'
permissions:
  contents: write
  actions: write
jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    env:
      STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_API_REFRESH_TOKEN: ${{ secrets.STRAVA_API_REFRESH_TOKEN }}
      GOOGLE_STATIC_MAPS_API_KEY: ${{ secrets.GOOGLE_STATIC_MAPS_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true      
      - run: _scripts/update.sh
      - name: Deploy updated site
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run deploy.yml --repo "$GITHUB_REPOSITORY" --ref gh-pages
