name: strava
on:
  workflow_dispatch:
  schedule:
    - cron: '00 01,13 * * *'
jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    env:
      STRAVA_CLIENT_ID: 23518
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_API_REFRESH_TOKEN: ${{ secrets.STRAVA_API_REFRESH_TOKEN }}
      GOOGLE_STATIC_MAPS_API_KEY: AIzaSyC1MId7bFpkLXNAaYhBSTb8jLyiSqzbDtM
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true      
      - run: _scripts/update.sh
